== Hprof notes

// blank line
:bl: pass:[ +]
:url-hprof-heap: https://github.com/oracle/visualvm/blob/9a43222f488b8f9e9fba71363c4bcd056c532948/visualvm/libs.profiler/lib.profiler/src/org/graalvm/visualvm/lib/jfluid/heap/HprofHeap.java#L70-L109
:url-hprof-manual: https://htmlpreview.github.io/?https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/demo/jvmti/hprof/manual.html#mozTocId848088
:url-hprof-parser-jdk: https://github.com/AdoptOpenJDK/openjdk-jdk/tree/91b2aa3f4f5f7c189815dd5d403f55dd71885bb9/test/lib/jdk/test/lib/hprof
:url-hprof-heapreader: https://github.com/AdoptOpenJDK/openjdk-jdk/blob/c54977543bd2c1e3d9e5b7aeaf0464853d0f16b7/test/lib/jdk/test/lib/hprof/parser/HprofReader.java

.{url-hprof-heap}[Hprof heap tags]
[source]
----
    // dump tags
    static final int STRING = 1;
    static final int LOAD_CLASS = 2;
    private static final int UNLOAD_CLASS = 3;
    static final int STACK_FRAME = 4;
    static final int STACK_TRACE = 5;
    private static final int ALLOC_SITES = 6;
    static final int HEAP_SUMMARY = 7;
    private static final int START_THREAD = 0xa;
    private static final int END_THREAD = 0xb;
    private static final int HEAP_DUMP = 0xc;
    private static final int HEAP_DUMP_SEGMENT = 0x1c;
    private static final int HEAP_DUMP_END = 0x2c;
    private static final int CPU_SAMPLES = 0xd;
    private static final int CONTROL_SETTINGS = 0xe;

    // heap dump tags
    static final int ROOT_UNKNOWN = 0xff;
    static final int ROOT_JNI_GLOBAL = 1;
    static final int ROOT_JNI_LOCAL = 2;
    static final int ROOT_JAVA_FRAME = 3;
    static final int ROOT_NATIVE_STACK = 4;
    static final int ROOT_STICKY_CLASS = 5;
    static final int ROOT_THREAD_BLOCK = 6;
    static final int ROOT_MONITOR_USED = 7;
    static final int ROOT_THREAD_OBJECT = 8;
    static final int CLASS_DUMP = 0x20;
    static final int INSTANCE_DUMP = 0x21;
    static final int OBJECT_ARRAY_DUMP = 0x22;
    static final int PRIMITIVE_ARRAY_DUMP = 0x23;

    //  HPROF HEAP 1.0.3 tags
    static final int HEAP_DUMP_INFO                = 0xfe;
    static final int ROOT_INTERNED_STRING          = 0x89;
    static final int ROOT_FINALIZING               = 0x8a;
    static final int ROOT_DEBUGGER                 = 0x8b;
    static final int ROOT_REFERENCE_CLEANUP        = 0x8c;
    static final int ROOT_VM_INTERNAL              = 0x8d;
    static final int ROOT_JNI_MONITOR              = 0x8e;
    static final int UNREACHABLE                   = 0x90; /* deprecated */
    static final int PRIMITIVE_ARRAY_NODATA_DUMP   = 0xc3;

    // basic type
    static final int OBJECT = 2;
    static final int BOOLEAN = 4;
    static final int CHAR = 5;
    static final int FLOAT = 6;
    static final int DOUBLE = 7;
    static final int BYTE = 8;
    static final int SHORT = 9;
    static final int INT = 10;
    static final int LONG = 11;
    private static final boolean DEBUG = false;
----


== Binary Dump Format (format=b)
{url-hprof-manual}[source]

The basic fields in the binary output are

* `u1` (1 byte)
* `u2` (2 byte)
* `u4` (4 byte)
* `u8` (8 byte)

An _ID_ in this implementation is a `u4`, however the size of an ID is
really determined by the "size of identifiers" field in the header.

WARNING: The hprof manual page indicates this warning, as this format is
considered highly experimental.

The binary output begins with the information:

.hprof format
[cols="1m,6a"]
|===

| [u1]*
| An initial `NULL` terminated series of bytes representing the format name
and version, in this implementation and historically, the string
`JAVA PROFILE 1.0.1` (18 `u1` bytes) followed by a NULL byte.
If the TAG "HEAP DUMP SEGMENT" is used this string will be `JAVA PROFILE 1.0.2`.

More specifically ({url-hprof-heapreader}#L61-L78[source]) :

* Version 1.0.1 added `HPROF_GC_PRIM_ARRAY_DUMP`, which requires no
version-sensitive parsing.
+
Version 1.0.1 changed the type of a constant pool entry from a signature
to a typecode.

* Version 1.0.2 added `HPROF_HEAP_DUMP_SEGMENT` and `HPROF_HEAP_DUMP_END`
to allow a large heap to be dumped as a sequence of heap dump segments.
+
The HPROF agent in J2SE 1.2 through to 5.0 generate a version 1.0.1
file. In Java SE 6.0 the version is either 1.0.1 or 1.0.2 depending on
the size of the heap (normally it will be 1.0.1 but for *multi-GB*
heaps the heap dump will not fit in a `HPROF_HEAP_DUMP` record so the
dump is generated as version 1.0.2).

In the JDK code {url-hprof-heapreader}#L52[here] and {url-hprof-heapreader}#L388-L412[here]
the versions of the hprof file correspond to

* `1.0`   -> VERSION_JDK12BETA3
* `1.0.1` -> VERSION_JDK12BETA4
* `1.0.2` -> VERSION_JDK6


| u4
| Size of identifiers. Identifiers are used to represent UTF8 strings, objects,
stack traces, etc. They can have the same size as host pointers or `sizeof(void*)`,
but are not required to be.

| u4
| high word of number of milliseconds since _0:00 GMT, 1/1/70_

| u4
| low word of number of milliseconds since _0:00 GMT, 1/1/70_

| [record]*
| a sequence of __record__s

|===


.record format
[cols="1m,6a"]
|===

| u1
| a TAG that denotes the type of the record

| u4
| number of *microseconds* since the time stamp in the header.
(It wraps around in a little more than an hour).
_Usually not useful for heap dumps._

| u4
| number of bytes *remaining* in the record. Note that this number
excludes the tag and the length fields itself.

| [u1]*
| The *body* of the record with as many bytes as specified in
the above u4 field

|===





The following __tag__s / __record__s are supported:

[cols="2m,1m,1m,5a"]
|===

.2+| STRING IN UTF8        .2+| 0x01

| ID                         a| ID for this string
| [u1]*                      a| UTF8 characters for string (NOT NULL terminated)

.4+| LOAD CLASS            .4+| 0x02

| u4                         a| class serial number (always > 0)
| ID                         a| class object ID
| u4                         a| stack trace serial number
| ID                         a| class name string ID

| UNLOAD CLASS                | 0x03

| u4                         a| class serial number

.6+| STACK FRAME           .6+| 0x04

| ID                         a| stack frame ID
| ID                         a| method name string ID
| ID                         a| method signature string ID
| ID                         a| source file name string ID
| u4                         a| class serial number
| u4                         a|

* > 0 =>line number
* 0 => no line information available
* -1 => unknown location
* -2 => compiled method (Not implemented)
* -3 => native method (Not implemented)

.4+| STACK TRACE
.4+| 0x05

| u4                         a| stack trace serial number
| u4                         a| thread serial number
| u4                         a| number of frames
| [ID]*                      a| series of stack frame ID's


.7+| ALLOC SITES           .7+| 0x06

| u2                          | Bit mask flags:

* 0x1 => incremental vs. complete
* 0x2 => sorted by allocation vs. line
* 0x4 => whether to force GC (Not Implemented)

| u4                         a| cutoff ratio (floating point)
| u4                         a| total live bytes
| u4                         a| total live instances
| u8                         a| total bytes allocated
| u8                         a| total instances allocated

| u4                         a| number of sites that follow:

.sites
[cols="1m,3a"]
!===

! u1          ! array indicator:

* 0 means not an array,
* non-zero means an array of this type (See Basic Type)

! u4          ! class serial number
! u4          ! stack trace serial number
! u4          ! number of live bytes
! u4          ! number of live instances
! u4          ! number of bytes allocated
! u4          ! number of instances allocated

!===

{bl}

.4+| HEAP SUMMARY          .4+| 0x07

| u4                         a| total live bytes
| u4                         a| total live instances
| u8                         a| total bytes allocated
| u8                         a| total instances allocated

.6+| START THREAD          .6+| 0x0A

| u4                         a| thread serial number
| ID                         a| thread object ID
| u4                         a| stack trace serial number
| ID                         a| thread name string ID
| ID                         a| thread group name ID
| ID                         a| thread parent group name ID

| END THREAD                  | 0x0B

| u4                         a| thread serial number

| HEAP DUMP {bl}
_or_ {bl}
HEAP DUMP SEGMENT
| 0x0C {bl}
{bl}
0x1C

2.+a| Contains any number of sub-tags, each begins a u1 field (no order implied here):

[cols="2m,1m,1m,4a"]
!===

! ROOT UNKNOWN                ! 0xFF
! ID                         a! object ID

.2+! ROOT JNI GLOBAL       .2+! 0x01
! ID                         a! object ID
! ID                         a! JNI global ref ID

.3+! ROOT JNI LOCAL        .3+! 0x02
! ID                         a! object ID
! u4                         a! thread serial number
! u4                         a! frame number in stack trace (-1 for empty)

.3+! ROOT JAVA FRAME       .3+! 0x03
! ID                         a! object ID
! u4                         a! thread serial number
! u4                         a! frame number in stack trace (-1 for empty)

.2+! ROOT NATIVE STACK     .2+! 0x04
! ID                         a! object ID
! u4                         a! thread serial number

! ROOT STICKY CLASS           ! 0x05
! ID                         a! object ID

.2+! ROOT THREAD BLOCK     .2+! 0x06
! ID                         a! object ID
! u4                         a! thread serial number

! ROOT MONITOR USED           ! 0x07
! ID                         a! object ID

.3+! ROOT THREAD OBJECT    .3+! 0x08
! ID                         a! thread object ID
! u4                         a! thread serial number
! u4                         a! stack trace serial number

.12+! CLASS DUMP         .12+! 0x20
! ID                         a! class object ID
! u4                         a! stack trace serial number
! ID                         a! super class object ID
! ID                         a! class loader object ID
! ID                         a! signers object ID
! ID                         a! protection domain object ID
! ID                         a! reserved
! ID                         a! reserved
! u4                         a! instance size (in bytes)
! u2                         a! size of constant pool and number of records that follow:

* `u2`   => constant pool index
* `u1`   => type of entry: (See Basic Type)
* value  => value of entry (u1, u2, u4, or u8 based on type of entry)


! u2                         a! Number of static fields:

* `ID`   => static field name string ID
* `u1`   => type of field: (See Basic Type)
* value  => value of entry (u1, u2, u4, or u8 based on type of field)

! u2                         a! Number of instance fields (not including super class's)

* `ID`   => field name string ID
* `u1`   => type of field: (See Basic Type)


.5+! INSTANCE DUMP         .5+! 0x21
! ID                         a! object ID
! u4                         a! stack trace serial number
! ID                         a! class object ID
! u4                         a! number of bytes that follow
! [value]*                   a! instance field values (this class, followed by super class, etc)

.5+! OBJECT ARRAY DUMP     .5+! 0x22
! ID                         a! array object ID
! u4                         a! stack trace serial number
! u4                         a! number of elements
! ID                         a! array class object ID
! [ID]*                      a! elements

.5+! PRIMITIVE ARRAY DUMP  .5+! 0x23
! ID                         a! array object ID
! u4                         a! stack trace serial number
! u4                         a! number of elements
! u1                         a! element type (See Basic Type)
! [u1]*                      a! elements (packed array)

!===

{bl}

| HEAP DUMP END               | 0x2C
2+a| Terminates a series of HEAP DUMP SEGMENTS.
{bl}
*Concatenation of HEAP DUMP SEGMENTS equals a HEAP DUMP.*

.4+| CPU SAMPLES           .4+| 0x0D
| u4                         a| total number of samples
| u4                         a| number of traces that follow:

.traces
[cols="1m,3a"]
!===

! u4          ! number of samples
! u4          ! stack trace serial number

!===

{bl}

.2+| CONTROL SETTINGS      .2+| 0x0E
| u4                         a| Bit mask flags:

* 0x1 => alloc traces on/off
* 0x2 => cpu sampling on/off

| u2                         a| stack trace depth

|===

.Basic Type
[options="header",cols="1m,2"]
|===

| (int) | type
| 2     | object
| 4     | boolean
| 5     | char
| 6     | float
| 7     | double
| 8     | byte
| 9     | short
| 10    | int
| 11    | long

|===

Handling of Arrays

There will be a "LOAD CLASS" tag for the type of each array in the dump. In the LOAD CLASS record, the class name string ID will refer to a string with a human-readable name of the array type that is formatted as the type name would be in Java source code. Thus, the LOAD CLASS record for the type char[] will be "char[]", for short[][][] will be "short[][][]" and for MyType[] will be "MyType[]".












== Debug info

debug level ? `2` or `1`