name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.0.java11'
      - run: gu install native-image
      - run: java --version
      - name: Build with Gradle
        run: ./gradlew --console=plain build
      - run: native-image --no-server -cp build/libs/qleak-*.jar